Объекты user и item созданы
ChertkovFedor/java-shareit pull request #1
Opened 2023-03-28 03:53 UTC by ChertkovFedor

2023-03-28 21:40 UTC, db-exp requested changes

2023-03-28 21:40 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>  public class ItemController {
Не хочешь начать использовать Valid для RequestBody?

2023-03-28 21:40 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/dto/ItemCreationDto.java
> +public class ItemCreationDto {
хорошо бы добавить ограничения по размерам/пустоте сразу на  dto

2023-03-28 21:40 UTC, db-exp commented on src/main/resources/application.properties
пока в этом спринте нет работы с базой - PostgreSQL и jpa излишни

2023-03-28 21:40 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/dto/UserCreationDto.java
> +public class UserCreationDto {
тот же вопрос как и для Item про ограничения на поля

2023-03-28 21:40 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/UserController.java
>  public class UserController {
Как и для ItemController я бы предложил использовать Valid на RequestBody для проверки dto

2023-03-29 17:59 UTC, ChertkovFedor commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>  public class ItemController {
Я изначально пытался использовать Valid, но тогда код ошибки становится 500 и в постмане не проходят тесты.
Плюс есть проблема с update. Там передается только та переменная. которая меняется, а остальные автоматически становятся null, что не пропускает Valid и программа не работает.
Не знаю как правильно решить эту проблему.
Можешь расписать?

2023-03-30 09:05 UTC, ChertkovFedor commented on src/main/resources/application.properties
Так как это было в исходном файле и пригодится в будущем, не стал удалять, а просто закоментил.

2023-03-30 09:10 UTC, ChertkovFedor commented
Не стал пока добавлять Valid к параметрам так как не до конца понимаю как решить конфликт возникающий с тестами постмана (написал об этом в комментарии ранее).
В следующем ТЗ (14 спринт) добавлю, если ситуация прояснится. Пока что мне написали, что мой вариант (который используется сейчас) допускается.

2023-03-30 12:27 UTC, db-exp requested changes

2023-03-30 12:27 UTC, db-exp commented on hs_err_pid18776.log
точно лишняя штука)

2023-03-30 17:56 UTC, db-exp approved these changes

2023-04-07 03:02 UTC, merged