Задание 14 выполнено
ChertkovFedor/java-shareit pull request #2
Opened 2023-04-14 15:08 UTC by ChertkovFedor

2023-04-15 13:03 UTC, db-exp requested changes

2023-04-15 13:03 UTC, db-exp commented on src/main/java/ru/practicum/shareit/comment/repository/CommentRepository.java
> +public interface CommentRepository extends JpaRepository<Comment, Long> {
не хватает аннотации Repository

2023-04-15 13:03 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Integer> {
не хватает аннотации Repository

2023-04-15 13:03 UTC, db-exp commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=none
PostgreSQL используется локально, для тестов нужно использовать h2

2023-04-15 13:03 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/dto/BookingCreationDto.java
> +    private Integer itemId;
можно Positive добавить

2023-04-15 13:03 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestBody BookingCreationDto bookingCreationDto,
давай Valid добавим?

2023-04-15 13:03 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +public interface BookingRepository extends JpaRepository<Booking, Integer> {
не хватает аннотации Repository

2023-04-15 13:03 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/dto/BookingForItemDto.java
> +public class BookingForItemDto {
тут тоже можно аннотаций валидации добавить и не проверять потом кодом

2023-04-15 13:03 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private final ItemService iServ;
молодец, что ходишь через сервисы, а не репозитории

2023-04-15 13:03 UTC, db-exp commented on src/main/java/ru/practicum/shareit/comment/dto/CommentCreateDto.java
> +    private String text;
тут лучше тоже добавить валидацию на размер

2023-04-15 13:03 UTC, db-exp commented on src/main/java/ru/practicum/shareit/comment/model/Comment.java
> +public class Comment {
Тут на String поле лучше добавить Size аннотацию

2023-04-15 13:03 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>  public class ItemController {
Давай на методы Valid добавим дляя RequestBody

2023-04-15 13:03 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>  public class Item {
Давай на String поля добавим Size

2023-04-15 13:03 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/model/User.java
>  public class User {
Давай на String поля добавим аннотацию Size

2023-04-15 13:03 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/UserController.java
>  public class UserController {
Давай добавим Valid для RequestBody

2023-04-16 02:31 UTC, ChertkovFedor commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Integer> {
Ты поставил этот коммент как раз на аннотацию Repository. Или я что-то не понимаю...

2023-04-18 08:37 UTC, ChertkovFedor commented
Аннотации с влидацией добавил, но вопрос такой же как и в прошлом задании. Как сделать так чтобы ошибка была допустим 400, а не 500? Постман не пропускает эту валидацию по тестам.

2023-04-18 08:37 UTC, ChertkovFedor commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=none
Здесь не до конца понимаю что нужно поменять

2023-04-18 10:17 UTC, db-exp commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=none
уже все ок!

2023-04-18 10:18 UTC, db-exp approved these changes

2023-04-19 07:28 UTC, merged